#!/bin/bash
# --------------------------------------------------------------------------------------------------
# XX-REVIEWD-XX      Startup script for the review server
#
# chkconfig: - 70 15
# description: Review is a process that will go to our production database and review all production\
#              requests and submit all remainders needed to complete thje request.
#
# processname: XX-REVIEWD-XX
# config:      /etc/XX-REVIEWD-XX.conf
# pidfile:     /var/run/XX-REVIEWD-XX.pid
# --------------------------------------------------------------------------------------------------
# Source function library.
. /etc/rc.d/init.d/functions

# This will prevent initlog from swallowing up a pass-phrase prompt if
# mod_ssl needs a pass-phrase from the user.
INITLOG_ARGS=""

# Path to the running script, server binary, and short-form for messages.
#reviewd=/usr/sbin/XX-REVIEWD-XX
reviewd=$MIT_PROD_AGENTS_BASE/reviewd
prog=XX-REVIEWD-XX
pidfile=${PIDFILE-/var/run/XX-REVIEWD-XX.pid}
lockfile=${LOCKFILE-/var/lock/subsys/XX-REVIEWD-XX}

RETVAL=0
STOP_TIMEOUT=${STOP_TIMEOUT-10}

# Start review daemon (XX-REVIEWD-XX)
start() {
    echo -n $"Starting $prog:"
    daemon --user=cmsprod --pidfile=${pidfile} $reviewd \&
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && touch ${lockfile}

    # this seems like a hack, but I do not know how to do it differently
    pid=`ps auxw | grep "/bin/bash $reviewd" |tr -s ' '|cut -d' ' -f2`
    echo $pid > $pidfile

    return $RETVAL
}

# Stop review daemon (XX-REVIEWD-XX)
stop() {
    echo -n $"Stopping $prog: "
    killproc -p ${pidfile} -d ${STOP_TIMEOUT} $reviewd
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status -p ${pidfile} $reviewd
    RETVAL=$?
    ;;
  restart)
    stop
    start
    ;;
  condrestart|try-restart)
    if status -p ${pidfile} $reviewd >&/dev/null
    then
      stop
      start
    fi
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|status|help}"
    RETVAL=2
esac

exit $RETVAL
