#!/bin/bash
# --------------------------------------------------------------------------------------------------
# uploadd      Startup script for the upload server
#
# chkconfig: - 70 15
# description: Upload is a process that will go to our specified storage and upload all to dropbox.
#
# processname: uploadd
# config:      /etc/uploadd.conf
# pidfile:     /var/run/uploadd.pid
# --------------------------------------------------------------------------------------------------
# Source function library.
. /etc/rc.d/init.d/functions

# This will prevent initlog from swallowing up a pass-phrase prompt if
# mod_ssl needs a pass-phrase from the user.
INITLOG_ARGS=""

# Path to the running script, server binary, and short-form for messages.
#uploadd=/usr/sbin/uploadd
uploadd=/usr/local/MitProd/agents/uploadd
prog=uploadd
pidfile=${PIDFILE-/var/run/uploadd.pid}
lockfile=${LOCKFILE-/var/lock/subsys/uploadd}

RETVAL=0
STOP_TIMEOUT=${STOP_TIMEOUT-10}

# Start upload daemon (uploadd)
start() {
    echo -n $"Starting $prog:"
    daemon --user=cmsprod --pidfile=${pidfile} $uploadd \&
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && touch ${lockfile}

    # this seems like a hack, but I do not know how to do it differently
    pid=`ps auxw | grep "/bin/bash $uploadd" |tr -s ' '|cut -d' ' -f2`
    echo $pid > $pidfile

    return $RETVAL
}

# Stop upload daemon (uploadd)
stop() {
    echo -n $"Stopping $prog: "
    killproc -p ${pidfile} -d ${STOP_TIMEOUT} $uploadd
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status -p ${pidfile} $uploadd
    RETVAL=$?
    ;;
  restart)
    stop
    start
    ;;
  condrestart|try-restart)
    if status -p ${pidfile} $uploadd >&/dev/null
    then
      stop
      start
    fi
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|status|help}"
    RETVAL=2
esac

exit $RETVAL
