#!/bin/bash
# --------------------------------------------------------------------------------------------------
# Process to keep cataloging alive and well.
#
# v1.0                                                                         C.Paus (Apr 27, 2015)
# --------------------------------------------------------------------------------------------------
# initialize environment variables
source $MIT_PROD_AGENTS_BASE/setupAgents.sh

# daemon
daemon=`basename $0`

# go to work area
cd $MIT_PROD_AGENTS_WORK
echo ""
echo " Work area: "`pwd`
echo ""

# infinite loop
while [ 1 ]
do

  # make sure the log directory exists
  mkdir -p $MIT_PROD_AGENTS_LOG/${daemon}
  if [ -e "$MIT_PROD_AGENTS_LOG/${daemon}" ]
  then
    #echo " Request review log area exists. Let's start!"
    sleep 1
  else
    echo ""
    echo " Request review area could not be found ($MIT_PROD_AGENTS_LOG). EXIT!"
    echo ""
    exit 1
  fi

  # generate specific log file
  tag=`date "+%s"`
  logFile=$MIT_PROD_AGENTS_LOG/${daemon}/${daemon}-$tag.log
  touch $logFile
  echo ""                                                                          >> $logFile
  echo " = = = =  I N I T I A L  M I T _ P R O D   E N V I R O N M E N T  = = = =" >> $logFile
  echo ""                                                                          >> $logFile
  env  | grep ^MIT_PROD                                                            >> $logFile
  echo ""                                                                          >> $logFile
  echo " = = = =  I N I T I A L  C A T A L O G  E N V I R O N M E N T  = = = ="    >> $logFile
  echo ""                                                                          >> $logFile
  env  | grep ^MIT_PROD_CATALOG                                                    >> $logFile
  echo ""                                                                          >> $logFile
  echo "[ PYTHON PATH: $PYTHONPATH ]"                                              >> $logFile
  echo ""                                                                          >> $logFile

  # ten loops over the process with one logfile (keep it small)
  for index in `echo 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19`
  do
    # period nSeconds
    let wait=$MIT_PROD_CATALOG_CYCLE_SECONDS

    echo " "                                                                      >> $logFile
    echo " catalog loop $index started -- $tag (cycle wait $wait sec)"            >> $logFile
    echo " "                                                                      >> $logFile
    echo "   --> "`date`                                                          >> $logFile
    echo " "                                                                      >> $logFile
    stdbuf -o0 -e0 $MIT_PROD_DIR/bin/jobSitter.py --catalog=2                     >> $logFile 2>&1

    echo " "                                                                      >> $logFile
    echo " completed review cycle."                                               >> $logFile
    echo " FINISH by updating log files on web."                                  >> $logFile

    # insure that the log information is updated
    mkdir -p $MIT_PROD_AGENTS_WWW 
    rsync -Cavz --delete $MIT_PROD_AGENTS_LOG/${daemon} $MIT_PROD_AGENTS_WWW      >> $logFile 2>&1

    sleep $wait
  done

done

exit 0;
