#!/bin/bash
# --------------------------------------------------------------------------------------------------
# Process to keep cleanup alive and well.
#
# v1.0                                                                         C.Paus (Apr 27, 2015)
# --------------------------------------------------------------------------------------------------
# initialize environment variables
source $MIT_PROD_AGENTS_BASE/setupAgents.sh

# daemon
daemon=`basename $0`
#daemonBanner=

# go to work area
cd $MIT_PROD_AGENTS_WORK
echo ""
echo " Work area: "`pwd`
echo ""

# infinite loop
while [ 1 ]
do

  # make sure the log directory exists
  mkdir -p $MIT_PROD_AGENTS_LOG/${daemon}
  if [ -e "$MIT_PROD_AGENTS_LOG/${daemon}" ]
  then
    #echo " Cleanup log area exists. Let's start!"
    sleep 1
  else
    echo ""
    echo " Log area could not be found ($MIT_PROD_AGENTS_LOG/${daemon}). EXIT!"
    echo ""
    exit 1
  fi

  # generate specific log file
  tag=`date "+%s"`
  logFile=$MIT_PROD_AGENTS_LOG/${daemon}/${daemon}.log
  rm -f $logFile
  touch $logFile
  echo ""                                                                          >> $logFile
  echo " = = = =  I N I T I A L  M I T _ P R O D   E N V I R O N M E N T  = = = =" >> $logFile
  echo ""                                                                          >> $logFile
  env  | grep ^MIT_PROD                                                            >> $logFile
  echo ""                                                                          >> $logFile
  echo " = = = =  I N I T I A L  C L E A N U P   E N V I R O N M E N T  = = = ="   >> $logFile
  echo ""                                                                          >> $logFile
  env  | grep ^MIT_PROD_CLEANUP                                                    >> $logFile
  echo ""                                                                          >> $logFile
  echo "[ PYTHON PATH: $PYTHONPATH ]"                                              >> $logFile
  echo ""                                                                          >> $logFile

  # ten loops over the process with one logfile (keep it small)
  for index in `echo 0 1 2 3 4 5 6 7 8 9`
  do
    # period nSeconds
    let wait=$MIT_PROD_CLEANUP_CYCLE_SECONDS

    echo " "                                                                      >> $logFile
    echo " = = = = loop $index started -- $tag (cycle wait $wait sec)"            >> $logFile
    echo " "                                                                      >> $logFile
    echo "   --> "`date`                                                          >> $logFile
    echo " "                                                                      >> $logFile
    stdbuf -o0 -e0 \
           $MIT_PROD_DIR/bin/jobSitter.py --catalog=0 --clean --writeSummary      >> $logFile 2>&1
    echo " completed ${daemon} cycle."                                            >> $logFile
    echo " FINISH by updating log files on web."                                  >> $logFile
    echo " "                                                                      >> $logFile

    # insure that the log information is updated
    mkdir -p $MIT_PROD_AGENTS_WWW 
    # sync the individual job file summary areas
    rsync -Cavz --delete $MIT_PROD_AGENTS_LOG/[0-9]??   $MIT_PROD_AGENTS_WWW      >> $logFile 2>&1
    # sync the daemon log file area
    rsync -Cavz --delete $MIT_PROD_AGENTS_LOG/${daemon} $MIT_PROD_AGENTS_WWW      >> $logFile 2>&1
    sleep $wait
  done

  # move log file to a dated version
  mv $logFile $MIT_PROD_AGENTS_LOG/${daemon}/${daemon}-${tag}.log

done

exit 0;
