#!/bin/bash
# --------------------------------------------------------------------------------------------------
# Process to keep request review alive and well.
#
# v1.0                                                                         C.Paus (Apr 27, 2015)
# --------------------------------------------------------------------------------------------------
# initialize environment variables
source $MIT_PROD_AGENTS_BASE/setupReview.sh

# go to work area
cd $MIT_PROD_REVIEW_WORK
echo ""
echo " Work area: "`pwd`
echo ""

# infinite loop
while [ 1 ]
do

  # make sure the log directory exists
  mkdir -p $MIT_PROD_REVIEW_LOG
  if [ -e "$MIT_PROD_REVIEW_LOG" ]
  then
    #echo " Request review log area exists. Let's start!"
    sleep 1
  else
    echo ""
    echo " Request review area could not be found ($MIT_PROD_REVIEW_LOG). EXIT!"
    echo ""
    exit 1
  fi

  # generate specific log file
  tag=`date "+%s"`
  logFile=$MIT_PROD_REVIEW_LOG/review-$tag.log
  touch $logFile
  echo ""                                                                      >> $logFile
  echo " = = = =  I N I T I A L  S H E L L   E N V I R O N M E N T  = = = ="   >> $logFile
  echo ""                                                                      >> $logFile
  env  | grep -v ^MIT_PROD_REVIEW                                              >> $logFile
  echo ""                                                                      >> $logFile
  echo " = = = =  I N I T I A L  R E V I E W   E N V I R O N M E N T  = = = =" >> $logFile
  echo ""                                                                      >> $logFile
  env  | grep ^MIT_PROD_REVIEW                                                 >> $logFile
  echo ""                                                                      >> $logFile
  echo "[ PYTHON PATH: $PYTHONPATH ]"                                          >> $logFile
  echo ""                                                                      >> $logFile

  # ten loops over the process with one logfile (keep it small)
  for index in `echo 0 1 2 3 4 5 6 7 8 9`
  do
    # period 3600 * nHours
    let wait=3600*$MIT_PROD_REVIEW_CYCLE_HOURS

    echo " "                                                                  >> $logFile
    echo " request review loop $index started -- $tag (cycle wait $wait sec)" >> $logFile
    echo " "                                                                  >> $logFile
    echo "   --> "`date`                                                      >> $logFile
    echo " "                                                                  >> $logFile
    cmssw=mc
    echo "   ==== cmssw: $cmssw"                                              >> $logFile
    echo " "                                                                  >> $logFile
    stdbuf -o0 -e0 $MIT_PROD_DIR/bin/reviewRequests.py --cmssw=$cmssw --updateCacheDb --exe \
                                                                              >> $logFile 2>&1
    echo " "                                                                  >> $logFile
    cmssw=mc-phys14
    echo "   ==== cmssw: $cmssw"                                              >> $logFile
    echo " "                                                                  >> $logFile
    stdbuf -o0 -e0 $MIT_PROD_DIR/bin/reviewRequests.py --cmssw=$cmssw --updateCacheDb --exe \
                                                                              >> $logFile 2>&1
    echo " completed review cycle."                                           >> $logFile
    echo " FINISH by updating log files on web."                              >> $logFile

    # insure that the log information is updated
    rsync -Cavz --delete $MIT_PROD_REVIEW_LOG \
                         /home/cmsprod/public_html/MitProd >& /dev/null

    sleep $wait
  done

done

exit 0;
